name: ticketing_sdk
description: A Dart SDK for seamless interaction with the TickeTing API. Use this to build Flutter applications with TickeTing integration.
version: 3.1.2
homepage: https://www.ticketingevents.com
repository: https://github.com/mitrakalloo/ticketing-nodejs-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.10.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
